# Generated by Django 6.0.2 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('what_to_do', models.TextField()),
                ('how_to_do', models.TextField()),
                ('when_to_do', models.TextField()),
            ],
        ),
    ]
